pipeline {
    agent any
    parameters {
        string(name: 'buildDescription', description: 'Bitte geben Sie den Grund für die Publikation der Daten ein')
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '25'))
        disableConcurrentBuilds()
        timeout(time: 3, unit: 'MINUTES')
    }
    stages {
        stage('Import into staging schema') {
            steps {
                script { currentBuild.description = "${params.buildDescription}" }
                git url: 'https://github.com/edigonzales/gretl-workshop-201900819'
                dir("exercise06") {
                    sh "./gradlew importNutzungsplanungToStage"
                    //archiveArtifacts artifacts: '*.xtf'
                }
                //echo "Send E-Mails (containing link to ${BUILD_URL}input/)"
            }
        }
        stage('Validation') {
            steps {
                input message: 'Sollen die Daten publiziert werden?'
            }
        }
        stage('Import into live schema') {
            steps {
                //git url: 'https://github.com/schmandr/oereb-gretljobs.git'
                //dir("exercise06") {
                    sh "./gradlew importNutzungsplanungToLive"
                    archiveArtifacts artifacts: '*.xtf'
                //}
            }
        }
       
    }
    post {
        always {
            echo 'deleteDir()'
        }
        failure {
            echo 'Send E-Mail'
        }
    }
}